### PR TITLE
fix #6 add support for promises

### LINKED ISSUE #6: when wrapped test returns promise, restore() shouldn't be called until it resolves
Problem is that the promise returned by the test calls the spied upon method asyncrhonously - however by then the proxy has been removed and then the chained asyncrhonous check on the spy fails. 

I propose that when return is a promise, then "finally" is used to restore wrapped methods, rather than restoring them syncrhonously. Does this sound right? (can create PR...)

### PR DESCRIPTION
**Pull request by RobertWHurst**
Adds support for promises. If a promise is returned from the callback then stubs will not be reset until after the promise is resolved/rejected. The promise is also proxied completely so values/errors will be received by code outside of sinon.test.

### CODE REVIEW

**Comment by RobertWHurst** [comment]
Seems to be something wrong with the version of phantomjs on the build server. I had this same issue with the packaged tests getting stuck at 33%. I installed the latest version of phantom and the issue went away.

screen shot 2016-04-15 at 6 00 01 pm

**Comment by RobertWHurst** [comment]
Fixed the issue by adding phantomjs as a dependency. The Travis server is now using the latest version of phantomjs.

**Comment by RobertWHurst** [comment]
@mroderick, @fatso83 any thoughts on this feature?

File: test/test-test.js [hunk 1]
```diff
@@ -107,6 +108,59 @@ buster.testCase("sinon-test", {
...
+    "restores stub after promise resolves": function (done) {
+        var object = {};
+
+        var promise = instance(function () {
+            return new Promise(function (resolve) {
+                nextTick(function () { resolve(object); });
+            });
+        }).call({});
+
+        promise.then(function (result) {
```
Comment (mroderick) [inline test/test-test.js]: You can `return` the promise, and skip the `done()`

**Comment by mroderick** [comment]
Other than a stylistic comment, which is not a big deal, I think this looks great :rocket

**Comment by mroderick** [comment]
As in, if you disagree, just merge as is

File: test/test-test.js (hunk 1 above)
Comment (RobertWHurst) [inline test/test-test.js]: Good to know. I haven't used buster before. I'll update that.

Comment (mroderick) [inline test/test-test.js]: It also works with Mocha, Ava. I imagine that it probably works in most modern test runners

**Comment by fatso83** [comment]
Thanks for diving into this and clearing things up, @RobertWHurst!
